[project]
name = "yxs-filter"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "openpyxl>=3.1.5",
    "pandas>=2.3.1",
    "pyinstaller>=6.14.2",
]
